apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: rkdr7ereq-python-gitops
  description: This is GitOps manifest for rkdr7ereq-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=rkdr7ereq-python
    backstage.io/kubernetes-id: rkdr7ereq-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: rkdr7ereq-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:rkdr7ereq-python
