apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rkdr7ereq-python
  janus-idp.io/tekton: rkdr7ereq-python
  backstage.io/kubernetes-id: rkdr7ereq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rkdr7ereq-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
