apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rkdr7ereq-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rkdr7ereq-python 
  name: rkdr7ereq-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rkdr7ereq-python 
